module.exports = (country) => {
  switch (country) {
  case "Algeria": return "🇩🇿";
  case "Antigua and Barbuda": return "🇦🇬";
  case "Argentina": return "🇦🇷";
  case "Australia": return "🇦🇺";
  case "Austria": return "🇦🇹";
  case "Bahamas": return "🇧🇸";
  case "Bahrain": return "🇧🇭";
  case "Bangladesh": return "🇧🇩";
  case "Barbados": return "🇧🇧";
  case "Belarus": return "🇧🇾";
  case "Belgium": return "🇧🇪";
  case "Bhutan": return "🇧🇹";
  case "Bolivia": return "🇧🇴";
  case "Brazil": return "🇧🇷";
  case "Cameroon": return "🇨🇲";
  case "Canada": return "🇨🇦";
  case "Chile": return "🇨🇱";
  case "China": return "🇨🇳";
  case "Colombia": return "🇨🇴";
  case "Costa Rica": return "🇨🇷";
  case "Croatia": return "🇭🇷";
  case "Cuba": return "🇨🇺";
  case "Czech Republic": return "🇨🇿";
  case "Denmark": return "🇩🇰";
  case "Dominican Republic": return "🇩🇴";
  case "Ecuador": return "🇪🇨";
  case "Egypt": return "🇪🇬";
  case "El Salvador": return "🇸🇻";
  case "Ethiopia": return "🇪🇹";
  case "Finland": return "🇫🇮";
  case "France": return "🇫🇷";
  case "Germany": return "🇩🇪";
  case "Ghana": return "🇬🇭";
  case "Greece": return "🇬🇷";
  case "Grenada": return "🇬🇩";
  case "Hungary": return "🇭🇺";
  case "Iceland": return "🇮🇸";
  case "India": return "🇮🇳";
  case "Indonesia": return "🇮🇩";
  case "Iraq": return "🇮🇶";
  case "Ireland": return "🇮🇪";
  case "Israel": return "🇮🇱";
  case "Italy": return "🇮🇹";
  case "Jamaica": return "🇯🇲";
  case "Japan": return "🇯🇵";
  case "Jordan": return "🇯🇴";
  case "Kazakhstan": return "🇰🇿";
  case "Kenya": return "🇰🇪";
  case "Kuwait": return "🇰🇼";
  case "Latvia": return "🇱🇻";
  case "Lebanon": return "🇱🇧";
  case "Malaysia": return "🇲🇾";
  case "Maldives": return "🇲🇻";
  case "Mexico": return "🇲🇽";
  case "Morocco": return "🇲🇦";
  case "Nepal": return "🇳🇵";
  case "Netherlands": return "🇳🇱";
  case "New Zealand": return "🇳🇿";
  case "Nicaragua": return "🇳🇮";
  case "Nigeria": return "🇳🇬";
  case "Norway": return "🇳🇴";
  case "Oman": return "🇴🇲";
  case "Pakistan": return "🇵🇰";
  case "Panama": return "🇵🇦";
  case "Paraguay": return "🇵🇾";
  case "Peru": return "🇵🇪";
  case "Philippines": return "🇵🇭";
  case "Poland": return "🇵🇱";
  case "Portugal": return "🇵🇹";
  case "Puerto Rico": return "🇵🇷";
  case "Qatar": return "🇶🇦";
  case "Romania": return "🇷🇴";
  case "Russia": return "🇷🇺";
  case "Saudi Arabia": return "🇸🇦";
  case "Senegal": return "🇸🇳";
  case "Singapore": return "🇸🇬";
  case "Slovakia": return "🇸🇰";
  case "Slovenia": return "🇸🇮";
  case "South Africa": return "🇿🇦";
  case "South Korea": return "🇰🇷";
  case "Spain": return "🇪🇸";
  case "Sri Lanka": return "🇱🇰";
  case "Sweden": return "🇸🇪";
  case "Switzerland": return "🇨🇭";
  case "Tanzania": return "🇹🇿";
  case "Thailand": return "🇹🇭";
  case "Trinidad and Tobago": return "🇹🇹";
  case "Tunisia": return "🇹🇳";
  case "Turkey": return "🇹🇷";
  case "Ukraine": return "🇺🇦";
  case "United Arab Emirates": return "🇦🇪";
  case "United Kingdom": return "🇬🇧";
  case "The United States": return "🇺🇸";
  case "Uruguay": return "🇺🇾";
  case "Venezuela": return "🇻🇪";
  case "Vietnam": return "🇻🇳";
  case "Yemen": return "🇾🇪";

  default: return "🏳️";
  }
};
